### ISSUE TITLE
Change pron display

### ISSUE THREAD

**Issue by siewyeng** [singdict/singdict.github.io#11]
![image](https://github.com/singdict/singdict.github.io/assets/59408288/9b349f32-14a0-4ba2-beac-c61ca954c5c2)
Currently, alternate prons for the same word are listed side by side even though they are separated by `\n` in the data file
![image](https://github.com/singdict/singdict.github.io/assets/59408288/34c6a518-3d3d-49e4-8ec5-2b2a61f6bc91)

I think it would be good to do a line separated display e.g.,
```
/bEN/
/beIN/
```
But that would probably mean having to place this somewhere else inside of beside the word? Or maybe something like
```
/bEN/, /beIN/
```

**Comment by fcbond** [comment]
Wiktionary does the latter:
`/ˈkɑːsəl/, /kɑːsl̩/`
